apiVersion: batch/v1
kind: Job
metadata:
  name: provisioning-credential-init
  namespace: system
spec:
  backoffLimit: 6
  template:
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: controller-manager
      containers:
      - name: credential-init
        image: controller:latest
        command:
        - /credential-init
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
          readOnlyRootFilesystem: true
