apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default

configMapGenerator:
- literals:
  - agentArtifactKeyID=release-agent-v1
  - osArtifactKeyID=release-v1
  - agentPlanKeyID=install-plan-v1
  name: tart-provisioning-settings
- files:
  - agent-artifact-public.pem=generated/agent-artifact-public.pem
  - os-artifact-public.pem=generated/os-artifact-public.pem
  name: provisioning-trust

generatorOptions:
  disableNameSuffixHash: true

patches:
- path: manager-patch.yaml
- path: generated/agent-artifact-patch.yaml
images:
- name: controller
  newName: controller
  newTag: latest
