package cluster

import (
	"errors"
	"fmt"
	"strings"
	"uuid"

	"github.com/walnuts1018/cluster-api-provider-tart/domain/textmarshal"
)

var ErrInvalidID = errors.New("invalid cluster ID")

// ClusterIDはTartClusterに割り当てられた永続的な識別子である。
type ClusterID uuid.UUID

// ParseClusterIDはCluster IDを検証して構築する。
func ParseClusterID(value string) (ClusterID, error) {
	parsed, err := uuid.Parse(strings.TrimSpace(value))
	if err != nil || parsed == uuid.Nil() {
		return ClusterID{}, fmt.Errorf("%w: %q", ErrInvalidID, value)
	}
	return ClusterID(parsed), nil
}

// NewClusterIDは新しいCluster IDを生成する。
func NewClusterID() ClusterID {
	parsed, err := ParseClusterID(uuid.NewV4().String())
	if err != nil {
		panic("generated cluster ID failed validation")
	}
	return parsed
}

// IsZeroはCluster IDが未設定かを返す。
func (id ClusterID) IsZero() bool {
	return uuid.UUID(id) == uuid.Nil()
}

// StringはCluster IDの正規化済み表現を返す。
func (id ClusterID) String() string {
	return uuid.UUID(id).String()
}

func (id ClusterID) MarshalJSON() ([]byte, error) {
	return textmarshal.JSON(id.String())
}

func (id *ClusterID) UnmarshalJSON(value []byte) error {
	return textmarshal.UnmarshalJSON(value, id.UnmarshalText)
}

func (id ClusterID) MarshalText() ([]byte, error) {
	return []byte(id.String()), nil
}

// UnmarshalTextは、MarshalTextが書き出した表現を必ず読み戻せなければならない。ParseClusterIDは
// 新規入力の意味的な妥当性(Nil UUIDの拒否)まで検証するのに対し、UnmarshalTextはround-trip契約を
// 満たすため構文的に有効なUUID表現だけを検証する。ゼロ値のClusterIDをMarshal/Unmarshalしたときに
// ErrInvalidIDへ化けさせないためにこの区別が必要である。
func (id *ClusterID) UnmarshalText(value []byte) error {
	if len(value) == 0 {
		*id = ClusterID{}
		return nil
	}
	parsed, err := uuid.Parse(strings.TrimSpace(string(value)))
	if err != nil {
		return fmt.Errorf("%w: %q", ErrInvalidID, value)
	}
	*id = ClusterID(parsed)
	return nil
}

// DeepCopyIntoはautogenerated deepcopyを満たすためのshallow copyである。ClusterIDの実体は
// 固定長byte配列(uuid.UUID)であり参照を持たないため、値のコピーだけで十分である。
func (id *ClusterID) DeepCopyInto(out *ClusterID) {
	*out = *id
}

// DeepCopyはClusterIDのdeep copyを返す。
func (id *ClusterID) DeepCopy() *ClusterID {
	if id == nil {
		return nil
	}
	out := new(ClusterID)
	id.DeepCopyInto(out)
	return out
}
