[Config]
MinimumVersion=26

[Distribution]
Distribution=ubuntu
Release=noble
Architecture=x86-64
Repositories=universe

[Output]
Format=disk
Output=tart-ubuntu-24.04-amd64
OutputDirectory=mkosi.output
CompressOutput=no
SplitArtifacts=partitions,roothash,kernel,initrd
ManifestFormat=json

[Content]
ExtraTrees=mkosi.extra
Packages=initramfs-tools
         cryptsetup-initramfs
         systemd-boot
         cloud-init
         containerd
         conntrack
         curl
         ebtables
         ethtool
         socat
         # renovate: datasource=github-tags depName=kubernetes/kubernetes
         kubeadm=1.37.0-2.1
         # renovate: datasource=github-tags depName=kubernetes/kubernetes
         kubectl=1.37.0-2.1
         # renovate: datasource=github-tags depName=kubernetes/kubernetes
         kubelet=1.37.0-2.1
         # renovate: datasource=github-tags depName=containernetworking/plugins
         kubernetes-cni=1.9.1-1.1
         # renovate: datasource=github-tags depName=kubernetes-sigs/cri-tools
         cri-tools=1.36.0-1.1
WithRecommends=no
CleanPackageMetadata=yes
Bootable=yes
# TODO: Task 01のboot trial比較完了後、Platform Profileで採用したbootloaderへ合わせる。
Bootloader=systemd-boot

[Build]
Incremental=no
