[Config]
MinimumVersion=26

[Distribution]
Distribution=ubuntu
Release=noble
Architecture=x86-64
Repositories=universe

[Output]
Format=disk
Output=tart-ubuntu-24.04-amd64
OutputDirectory=mkosi.output
CompressOutput=no
SplitArtifacts=partitions,roothash,kernel,initrd
ManifestFormat=json

[Content]
Packages=ubuntu-minimal
         linux-generic
         initramfs-tools
         cryptsetup-initramfs
         systemd-boot
         cloud-init
         containerd
         conntrack
         ebtables
         ethtool
         socat
         kubeadm=1.35.0-1.1
         kubectl=1.35.0-1.1
         kubelet=1.35.0-1.1
         kubernetes-cni=1.8.0-1.1
         cri-tools=1.35.0-1.1
WithRecommends=no
CleanPackageMetadata=yes
Bootable=yes
Bootloader=systemd-boot

[Build]
Incremental=no
