resources:
# All RBAC will be applied under this service account in
# the deployment namespace. You may comment out this resource
# if your manager will use a service account that exists at
# runtime. Be sure to update RoleBinding and ClusterRoleBinding
# subjects if changing service account names.
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
# The following RBAC configurations are used to protect
# the metrics endpoint with authn/authz. These configurations
# ensure that only authorized users and service accounts
# can access the metrics endpoint. Comment the following
# permissions if you want to disable this protection.
# More info: https://book.kubebuilder.io/reference/metrics.html
- metrics_auth_role.yaml
- metrics_auth_role_binding.yaml
- metrics_reader_role.yaml
- tart-host_admin_role.yaml
- tart-host_editor_role.yaml
- tart-host_viewer_role.yaml
- tart-machine_admin_role.yaml
- tart-machine_editor_role.yaml
- tart-machine_viewer_role.yaml
- tart-machine-template_admin_role.yaml
- tart-machine-template_editor_role.yaml
- tart-machine-template_viewer_role.yaml
- tart-cluster_admin_role.yaml
- tart-cluster_editor_role.yaml
- tart-cluster_viewer_role.yaml
- tart-cluster-template_admin_role.yaml
- tart-cluster-template_editor_role.yaml
- tart-cluster-template_viewer_role.yaml
- tart-bootstrap-config_admin_role.yaml
- tart-bootstrap-config_editor_role.yaml
- tart-bootstrap-config_viewer_role.yaml
- tart-bootstrap-config-template_admin_role.yaml
- tart-bootstrap-config-template_editor_role.yaml
- tart-bootstrap-config-template_viewer_role.yaml
- tart-control-plane_admin_role.yaml
- tart-control-plane_editor_role.yaml
- tart-control-plane_viewer_role.yaml
- tart-control-plane-template_admin_role.yaml
- tart-control-plane-template_editor_role.yaml
- tart-control-plane-template_viewer_role.yaml

labels:
- includeSelectors: true
  pairs:
    cluster.x-k8s.io/provider: infrastructure-tart
