apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-tart
    app.kubernetes.io/managed-by: kustomize
    cluster.x-k8s.io/provider: infrastructure-tart
  name: controller-manager
  namespace: system
