# This rule is not used by the project cluster-api-provider-tart itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to controlplane.cluster.x-k8s.io/tartcontrolplanes resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-tart
    app.kubernetes.io/managed-by: kustomize
  name: tart-control-plane-viewer-role
rules:
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - tartcontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - tartcontrolplanes/status
  verbs:
  - get
