// Code generated by kessoku. DO NOT EDIT.

package kessoku

import (
	"github.com/mazrean/kessoku"
	"github.com/walnuts1018/cluster-api-provider-tart/adapter/talos/configbuilder"
	"github.com/walnuts1018/cluster-api-provider-tart/controller/tartbootstrapconfig"
	"github.com/walnuts1018/cluster-api-provider-tart/usecase/bootstrap"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

func InitializeBootstrapReconcilers(client0 client.Client) BootstrapReconcilers {
	builder := kessoku.Bind[bootstrap.ConfigRenderer](kessoku.Provide(configbuilder.NewBuilder)).Fn()()
	tartBootstrapConfigReconciler := kessoku.Provide(tartbootstrapconfig.NewTartBootstrapConfigReconciler).Fn()(client0, builder)
	bootstrapReconcilers := kessoku.Provide(provideBootstrapReconcilers).Fn()(tartBootstrapConfigReconciler)
	return bootstrapReconcilers
}
