// Code generated by kessoku. DO NOT EDIT.

package kessoku

import (
	"github.com/mazrean/kessoku"
	"github.com/walnuts1018/cluster-api-provider-tart/controller/tartcontrolplane"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

func InitializeControlPlaneReconcilers(client0 client.Client) ControlPlaneReconcilers {
	tartControlPlaneReconciler := kessoku.Provide(tartcontrolplane.NewTartControlPlaneReconciler).Fn()(client0)
	controlPlaneReconcilers := kessoku.Provide(provideControlPlaneReconcilers).Fn()(tartControlPlaneReconciler)
	return controlPlaneReconcilers
}
