// Code generated by kessoku. DO NOT EDIT.

package kessoku

import (
	"github.com/mazrean/kessoku"
	"github.com/walnuts1018/cluster-api-provider-tart/controller/talosrecovery"
	"github.com/walnuts1018/cluster-api-provider-tart/controller/tartcluster"
	"github.com/walnuts1018/cluster-api-provider-tart/controller/tarthost"
	"github.com/walnuts1018/cluster-api-provider-tart/controller/tartmachine"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

func InitializeInfrastructureReconcilers(client0 client.Client) InfrastructureReconcilers {
	tartHostReconciler := kessoku.Provide(tarthost.NewTartHostReconciler).Fn()(client0)
	tartClusterReconciler := kessoku.Provide(tartcluster.NewTartClusterReconciler).Fn()(client0)
	tartMachineReconciler := kessoku.Provide(tartmachine.NewTartMachineReconciler).Fn()(client0)
	talosRecoveryReconciler := kessoku.Provide(talosrecovery.NewTalosRecoveryReconciler).Fn()(client0)
	infrastructureReconcilers := kessoku.Provide(provideInfrastructureReconcilers).Fn()(tartHostReconciler, tartClusterReconciler, tartMachineReconciler, talosRecoveryReconciler)
	return infrastructureReconcilers
}
