// Code generated by kessoku. DO NOT EDIT.

package kessoku

import (
	"github.com/mazrean/kessoku"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

func InitializeReconcilers(client0 client.Client) Reconcilers {
	tartHostReconciler := kessoku.Provide(provideTartHostReconciler).Fn()(client0)
	tartClusterReconciler := kessoku.Provide(provideTartClusterReconciler).Fn()(client0)
	tartMachineReconciler := kessoku.Provide(provideTartMachineReconciler).Fn()(client0)
	tartBootstrapConfigReconciler := kessoku.Provide(provideTartBootstrapConfigReconciler).Fn()(client0)
	tartControlPlaneReconciler := kessoku.Provide(provideTartControlPlaneReconciler).Fn()(client0)
	reconcilers := kessoku.Provide(provideReconcilers).Fn()(tartHostReconciler, tartClusterReconciler, tartMachineReconciler, tartBootstrapConfigReconciler, tartControlPlaneReconciler)
	return reconcilers
}
