apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: tart-k3s-debian
spec:
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: TartCluster
    name: tart-k3s-debian
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: TartCluster
metadata:
  name: tart-k3s-debian
spec: {}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: TartMachineTemplate
metadata:
  name: tart-k3s-debian-control-plane
spec:
  template:
    spec:
      image: http://cluster-api-provider-tart-controller-manager-ipxe.cluster-api-provider-tart-system.svc.cluster.local:8082/assets/images/debian-13-amd64.raw
      bootstrap:
        format: NoCloud
      kernelParams:
      - console=tty0
      - ip=dhcp
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: TartMachineTemplate
metadata:
  name: tart-k3s-debian-md-0
spec:
  template:
    spec:
      image: http://cluster-api-provider-tart-controller-manager-ipxe.cluster-api-provider-tart-system.svc.cluster.local:8082/assets/images/debian-13-amd64.raw
      bootstrap:
        format: NoCloud
      kernelParams:
      - console=tty0
      - ip=dhcp
