apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: tart-kubeadm-debian
  labels:
    cluster.x-k8s.io/cluster-name: tart-kubeadm-debian
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.0.0.0/16
    services:
    - 10.96.0.0/12
  controlPlaneEndpoint:
    host: 192.168.100.100
    port: 6443
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KubeadmControlPlane
    name: tart-kubeadm-debian-control-plane
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: TartCluster
    name: tart-kubeadm-debian
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: TartCluster
metadata:
  name: tart-kubeadm-debian
  labels:
    cluster.x-k8s.io/cluster-name: tart-kubeadm-debian
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlane
metadata:
  name: tart-kubeadm-debian-control-plane
spec:
  replicas: 1
  version: v1.35.4
  machineTemplate:
    spec:
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: TartMachineTemplate
        name: tart-kubeadm-debian-control-plane
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: TartMachineTemplate
metadata:
  name: tart-kubeadm-debian-control-plane
spec:
  template:
    spec:
      image: https://deb.debian.org/debian/dists/trixie/main/installer-amd64/current/images/netboot/debian-installer/amd64/linux
      initrd: https://deb.debian.org/debian/dists/trixie/main/installer-amd64/current/images/netboot/debian-installer/amd64/initrd.gz
      bootstrap:
        format: Preseed
      kernelParams:
      - console=ttyS0
      - ip=dhcp
      - interface=auto
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: tart-kubeadm-debian-md-0
spec:
  clusterName: tart-kubeadm-debian
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      clusterName: tart-kubeadm-debian
      version: v1.35.4
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: tart-kubeadm-debian-md-0
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: TartMachineTemplate
        name: tart-kubeadm-debian-md-0
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: tart-kubeadm-debian-md-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: TartMachineTemplate
metadata:
  name: tart-kubeadm-debian-md-0
spec:
  template:
    spec:
      image: https://deb.debian.org/debian/dists/trixie/main/installer-amd64/current/images/netboot/debian-installer/amd64/linux
      initrd: https://deb.debian.org/debian/dists/trixie/main/installer-amd64/current/images/netboot/debian-installer/amd64/initrd.gz
      bootstrap:
        format: Preseed
      kernelParams:
      - console=ttyS0
      - ip=dhcp
      - interface=auto
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineHealthCheck
metadata:
  name: tart-kubeadm-debian-md-0-health-check
  namespace: default
spec:
  clusterName: tart-kubeadm-debian
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: tart-kubeadm-debian
