apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: tart-kubeadm-ubuntu
  labels:
    cluster.x-k8s.io/cluster-name: tart-kubeadm-ubuntu
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.0.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneEndpoint:
    host: 192.168.100.100
    port: 6443
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KubeadmControlPlane
    name: tart-kubeadm-ubuntu-control-plane
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: TartCluster
    name: tart-kubeadm-ubuntu
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: TartCluster
metadata:
  name: tart-kubeadm-ubuntu
  labels:
    cluster.x-k8s.io/cluster-name: tart-kubeadm-ubuntu
spec:
  artifactPolicy:
    allowedRegistries:
    - registry.sample.walnuts.dev
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlane
metadata:
  name: tart-kubeadm-ubuntu-control-plane
spec:
  replicas: 1
  version: v1.37.0
  machineTemplate:
    spec:
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: TartMachineTemplate
        name: tart-kubeadm-ubuntu-control-plane
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: TartMachineTemplate
metadata:
  name: tart-kubeadm-ubuntu-control-plane
spec:
  template:
    spec:
      image:
        ref: oci://registry.sample.walnuts.dev/tart/ubuntu@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      platformProfile: amd64-uefi-ab-ubuntu-24.04-kubeadm/v1
      updatePolicy:
        mode: Replace
      deletionPolicy: WipeAll
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: tart-kubeadm-ubuntu-md-0
spec:
  clusterName: tart-kubeadm-ubuntu
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      clusterName: tart-kubeadm-ubuntu
      version: v1.37.0
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: tart-kubeadm-ubuntu-md-0
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: TartMachineTemplate
        name: tart-kubeadm-ubuntu-md-0
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: tart-kubeadm-ubuntu-md-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: TartMachineTemplate
metadata:
  name: tart-kubeadm-ubuntu-md-0
spec:
  template:
    spec:
      image:
        ref: oci://registry.sample.walnuts.dev/tart/ubuntu@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      platformProfile: amd64-uefi-ab-ubuntu-24.04-kubeadm/v1
      updatePolicy:
        mode: Replace
      deletionPolicy: WipeAll
