apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: tart-kubeadm-ubuntu
  labels:
    cluster.x-k8s.io/cluster-name: tart-kubeadm-ubuntu
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.0.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneEndpoint:
    host: 192.168.100.100
    port: 6443
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KubeadmControlPlane
    name: tart-kubeadm-ubuntu-control-plane
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: TartCluster
    name: tart-kubeadm-ubuntu
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: TartCluster
metadata:
  name: tart-kubeadm-ubuntu
  labels:
    cluster.x-k8s.io/cluster-name: tart-kubeadm-ubuntu
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlane
metadata:
  name: tart-kubeadm-ubuntu-control-plane
spec:
  replicas: 1
  version: v1.35.4
  machineTemplate:
    spec:
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: TartMachineTemplate
        name: tart-kubeadm-ubuntu-control-plane
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: TartMachineTemplate
metadata:
  name: tart-kubeadm-ubuntu-control-plane
spec:
  template:
    spec:
      image: http://cluster-api-provider-tart-controller-manager-ipxe.cluster-api-provider-tart-system.svc.cluster.local:8082/assets/images/ubuntu-24.04-amd64.raw
      bootstrap:
        format: NoCloud
      kernelParams:
      - console=tty0
      - ip=dhcp
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: tart-kubeadm-ubuntu-md-0
spec:
  clusterName: tart-kubeadm-ubuntu
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      clusterName: tart-kubeadm-ubuntu
      version: v1.35.4
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: tart-kubeadm-ubuntu-md-0
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: TartMachineTemplate
        name: tart-kubeadm-ubuntu-md-0
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: tart-kubeadm-ubuntu-md-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: TartMachineTemplate
metadata:
  name: tart-kubeadm-ubuntu-md-0
spec:
  template:
    spec:
      image: http://cluster-api-provider-tart-controller-manager-ipxe.cluster-api-provider-tart-system.svc.cluster.local:8082/assets/images/ubuntu-24.04-amd64.raw
      bootstrap:
        format: NoCloud
      kernelParams:
      - console=tty0
      - ip=dhcp
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineHealthCheck
metadata:
  name: tart-kubeadm-ubuntu-md-0-health-check
  namespace: default
spec:
  clusterName: tart-kubeadm-ubuntu
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: tart-kubeadm-ubuntu
