apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: TartHost
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-tart
    app.kubernetes.io/managed-by: kustomize
  name: worker-01
spec:
  macAddress: "52:54:00:12:34:56"
  # PXE boot に使う NIC が別の場合だけ指定する
  bootMacAddress: "52:54:00:12:34:57"
