apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: TartHostOperation
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-tart
    app.kubernetes.io/managed-by: kustomize
  name: active-666ff6ccaa5b3c07feaa3a95d3a4bd2c46ac9e9abdb09ca9133528d
spec:
  operationID: 0197d640-8d00-7a65-b67f-3f7c42a6935f
  type: Provision
  hostRef:
    namespace: default
    name: tarthost-sample
    uid: 11111111-2222-3333-4444-555555555555
  machineRef:
    namespace: default
    name: tartmachine-sample
    uid: 66666666-7777-8888-9999-aaaaaaaaaaaa
  planDigest: sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  desiredObjectsDigest: sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  deadline: "2026-07-04T15:00:00Z"
