apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: TartClusterTemplate
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-tart
    app.kubernetes.io/managed-by: kustomize
  name: tartclustertemplate-sample
spec:
  template:
    metadata:
      labels:
        sample.walnuts.dev/profile: amd64-uefi
    spec:
      artifactPolicy:
        allowedRegistries:
        - registry.sample.walnuts.dev
