## Append samples of your project ##
resources:
- bootstrap-httproute.yaml
- cluster-kubeadm-ubuntu.yaml
- infrastructure_v1beta1_tarthostoperation.yaml
- infrastructure_v1beta1_tartcluster.yaml
- infrastructure_v1beta1_tartclustertemplate.yaml
- infrastructure_v1beta1_tartmachine.yaml
- infrastructure_v1beta1_tartmachinetemplate.yaml
- infrastructure_v1beta1_tarthost.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
