//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartBootstrapConfig) DeepCopyInto(out *TartBootstrapConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartBootstrapConfig.
func (in *TartBootstrapConfig) DeepCopy() *TartBootstrapConfig {
	if in == nil {
		return nil
	}
	out := new(TartBootstrapConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartBootstrapConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartBootstrapConfigInitializationStatus) DeepCopyInto(out *TartBootstrapConfigInitializationStatus) {
	*out = *in
	if in.DataSecretCreated != nil {
		in, out := &in.DataSecretCreated, &out.DataSecretCreated
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartBootstrapConfigInitializationStatus.
func (in *TartBootstrapConfigInitializationStatus) DeepCopy() *TartBootstrapConfigInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(TartBootstrapConfigInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartBootstrapConfigList) DeepCopyInto(out *TartBootstrapConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TartBootstrapConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartBootstrapConfigList.
func (in *TartBootstrapConfigList) DeepCopy() *TartBootstrapConfigList {
	if in == nil {
		return nil
	}
	out := new(TartBootstrapConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartBootstrapConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartBootstrapConfigSpec) DeepCopyInto(out *TartBootstrapConfigSpec) {
	*out = *in
	if in.ConfigSecretRef != nil {
		in, out := &in.ConfigSecretRef, &out.ConfigSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartBootstrapConfigSpec.
func (in *TartBootstrapConfigSpec) DeepCopy() *TartBootstrapConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TartBootstrapConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartBootstrapConfigStatus) DeepCopyInto(out *TartBootstrapConfigStatus) {
	*out = *in
	in.Initialization.DeepCopyInto(&out.Initialization)
	if in.DataSecretName != nil {
		in, out := &in.DataSecretName, &out.DataSecretName
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartBootstrapConfigStatus.
func (in *TartBootstrapConfigStatus) DeepCopy() *TartBootstrapConfigStatus {
	if in == nil {
		return nil
	}
	out := new(TartBootstrapConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartBootstrapConfigTemplate) DeepCopyInto(out *TartBootstrapConfigTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartBootstrapConfigTemplate.
func (in *TartBootstrapConfigTemplate) DeepCopy() *TartBootstrapConfigTemplate {
	if in == nil {
		return nil
	}
	out := new(TartBootstrapConfigTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartBootstrapConfigTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartBootstrapConfigTemplateList) DeepCopyInto(out *TartBootstrapConfigTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TartBootstrapConfigTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartBootstrapConfigTemplateList.
func (in *TartBootstrapConfigTemplateList) DeepCopy() *TartBootstrapConfigTemplateList {
	if in == nil {
		return nil
	}
	out := new(TartBootstrapConfigTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartBootstrapConfigTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartBootstrapConfigTemplateResource) DeepCopyInto(out *TartBootstrapConfigTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartBootstrapConfigTemplateResource.
func (in *TartBootstrapConfigTemplateResource) DeepCopy() *TartBootstrapConfigTemplateResource {
	if in == nil {
		return nil
	}
	out := new(TartBootstrapConfigTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartBootstrapConfigTemplateResourceSpec) DeepCopyInto(out *TartBootstrapConfigTemplateResourceSpec) {
	*out = *in
	if in.ConfigSecretRef != nil {
		in, out := &in.ConfigSecretRef, &out.ConfigSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartBootstrapConfigTemplateResourceSpec.
func (in *TartBootstrapConfigTemplateResourceSpec) DeepCopy() *TartBootstrapConfigTemplateResourceSpec {
	if in == nil {
		return nil
	}
	out := new(TartBootstrapConfigTemplateResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartBootstrapConfigTemplateSpec) DeepCopyInto(out *TartBootstrapConfigTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartBootstrapConfigTemplateSpec.
func (in *TartBootstrapConfigTemplateSpec) DeepCopy() *TartBootstrapConfigTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(TartBootstrapConfigTemplateSpec)
	in.DeepCopyInto(out)
	return out
}
