//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/cluster-api/api/core/v1beta2"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootAttempt) DeepCopyInto(out *BootAttempt) {
	*out = *in
	in.FirstObservedAt.DeepCopyInto(&out.FirstObservedAt)
	in.LastObservedAt.DeepCopyInto(&out.LastObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootAttempt.
func (in *BootAttempt) DeepCopy() *BootAttempt {
	if in == nil {
		return nil
	}
	out := new(BootAttempt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletionApproval) DeepCopyInto(out *DeletionApproval) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletionApproval.
func (in *DeletionApproval) DeepCopy() *DeletionApproval {
	if in == nil {
		return nil
	}
	out := new(DeletionApproval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskInventory) DeepCopyInto(out *DiskInventory) {
	*out = *in
	if in.Symlinks != nil {
		in, out := &in.Symlinks, &out.Symlinks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskInventory.
func (in *DiskInventory) DeepCopy() *DiskInventory {
	if in == nil {
		return nil
	}
	out := new(DiskInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostInventory) DeepCopyInto(out *HostInventory) {
	*out = *in
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]DiskInventory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkInterfaces != nil {
		in, out := &in.NetworkInterfaces, &out.NetworkInterfaces
		*out = make([]NetworkInterfaceInventory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostInventory.
func (in *HostInventory) DeepCopy() *HostInventory {
	if in == nil {
		return nil
	}
	out := new(HostInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostSelector) DeepCopyInto(out *HostSelector) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostSelector.
func (in *HostSelector) DeepCopy() *HostSelector {
	if in == nil {
		return nil
	}
	out := new(HostSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementNamespaceSecretReference) DeepCopyInto(out *ManagementNamespaceSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementNamespaceSecretReference.
func (in *ManagementNamespaceSecretReference) DeepCopy() *ManagementNamespaceSecretReference {
	if in == nil {
		return nil
	}
	out := new(ManagementNamespaceSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInterfaceInventory) DeepCopyInto(out *NetworkInterfaceInventory) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInterfaceInventory.
func (in *NetworkInterfaceInventory) DeepCopy() *NetworkInterfaceInventory {
	if in == nil {
		return nil
	}
	out := new(NetworkInterfaceInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerSpec) DeepCopyInto(out *PowerSpec) {
	*out = *in
	if in.Redfish != nil {
		in, out := &in.Redfish, &out.Redfish
		*out = new(RedfishPowerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.WakeOnLAN != nil {
		in, out := &in.WakeOnLAN, &out.WakeOnLAN
		*out = new(WakeOnLANPowerConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerSpec.
func (in *PowerSpec) DeepCopy() *PowerSpec {
	if in == nil {
		return nil
	}
	out := new(PowerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviousConsumerRef) DeepCopyInto(out *PreviousConsumerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviousConsumerRef.
func (in *PreviousConsumerRef) DeepCopy() *PreviousConsumerRef {
	if in == nil {
		return nil
	}
	out := new(PreviousConsumerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedfishPowerConfig) DeepCopyInto(out *RedfishPowerConfig) {
	*out = *in
	out.CredentialSecretRef = in.CredentialSecretRef
	if in.CASecretRef != nil {
		in, out := &in.CASecretRef, &out.CASecretRef
		*out = new(ManagementNamespaceSecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedfishPowerConfig.
func (in *RedfishPowerConfig) DeepCopy() *RedfishPowerConfig {
	if in == nil {
		return nil
	}
	out := new(RedfishPowerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReuseApproval) DeepCopyInto(out *ReuseApproval) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReuseApproval.
func (in *ReuseApproval) DeepCopy() *ReuseApproval {
	if in == nil {
		return nil
	}
	out := new(ReuseApproval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TalosImageSpec) DeepCopyInto(out *TalosImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TalosImageSpec.
func (in *TalosImageSpec) DeepCopy() *TalosImageSpec {
	if in == nil {
		return nil
	}
	out := new(TalosImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartCluster) DeepCopyInto(out *TartCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartCluster.
func (in *TartCluster) DeepCopy() *TartCluster {
	if in == nil {
		return nil
	}
	out := new(TartCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartClusterInitializationStatus) DeepCopyInto(out *TartClusterInitializationStatus) {
	*out = *in
	if in.Provisioned != nil {
		in, out := &in.Provisioned, &out.Provisioned
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartClusterInitializationStatus.
func (in *TartClusterInitializationStatus) DeepCopy() *TartClusterInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(TartClusterInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartClusterList) DeepCopyInto(out *TartClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TartCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartClusterList.
func (in *TartClusterList) DeepCopy() *TartClusterList {
	if in == nil {
		return nil
	}
	out := new(TartClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartClusterSpec) DeepCopyInto(out *TartClusterSpec) {
	*out = *in
	out.UpdatePolicy = in.UpdatePolicy
	if in.CARotationRequestedGeneration != nil {
		in, out := &in.CARotationRequestedGeneration, &out.CARotationRequestedGeneration
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartClusterSpec.
func (in *TartClusterSpec) DeepCopy() *TartClusterSpec {
	if in == nil {
		return nil
	}
	out := new(TartClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartClusterStatus) DeepCopyInto(out *TartClusterStatus) {
	*out = *in
	in.Initialization.DeepCopyInto(&out.Initialization)
	if in.FailureDomains != nil {
		in, out := &in.FailureDomains, &out.FailureDomains
		*out = make([]v1beta2.FailureDomain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartClusterStatus.
func (in *TartClusterStatus) DeepCopy() *TartClusterStatus {
	if in == nil {
		return nil
	}
	out := new(TartClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartClusterTemplate) DeepCopyInto(out *TartClusterTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartClusterTemplate.
func (in *TartClusterTemplate) DeepCopy() *TartClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(TartClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartClusterTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartClusterTemplateList) DeepCopyInto(out *TartClusterTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TartClusterTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartClusterTemplateList.
func (in *TartClusterTemplateList) DeepCopy() *TartClusterTemplateList {
	if in == nil {
		return nil
	}
	out := new(TartClusterTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartClusterTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartClusterTemplateResource) DeepCopyInto(out *TartClusterTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartClusterTemplateResource.
func (in *TartClusterTemplateResource) DeepCopy() *TartClusterTemplateResource {
	if in == nil {
		return nil
	}
	out := new(TartClusterTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartClusterTemplateResourceSpec) DeepCopyInto(out *TartClusterTemplateResourceSpec) {
	*out = *in
	out.UpdatePolicy = in.UpdatePolicy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartClusterTemplateResourceSpec.
func (in *TartClusterTemplateResourceSpec) DeepCopy() *TartClusterTemplateResourceSpec {
	if in == nil {
		return nil
	}
	out := new(TartClusterTemplateResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartClusterTemplateSpec) DeepCopyInto(out *TartClusterTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartClusterTemplateSpec.
func (in *TartClusterTemplateSpec) DeepCopy() *TartClusterTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(TartClusterTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartHost) DeepCopyInto(out *TartHost) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartHost.
func (in *TartHost) DeepCopy() *TartHost {
	if in == nil {
		return nil
	}
	out := new(TartHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartHost) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartHostList) DeepCopyInto(out *TartHostList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TartHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartHostList.
func (in *TartHostList) DeepCopy() *TartHostList {
	if in == nil {
		return nil
	}
	out := new(TartHostList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartHostList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartHostSpec) DeepCopyInto(out *TartHostSpec) {
	*out = *in
	in.Power.DeepCopyInto(&out.Power)
	if in.ConsumerRef != nil {
		in, out := &in.ConsumerRef, &out.ConsumerRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.PreviousConsumerRef != nil {
		in, out := &in.PreviousConsumerRef, &out.PreviousConsumerRef
		*out = new(PreviousConsumerRef)
		**out = **in
	}
	if in.ReuseApproval != nil {
		in, out := &in.ReuseApproval, &out.ReuseApproval
		*out = new(ReuseApproval)
		**out = **in
	}
	if in.DeletionApproval != nil {
		in, out := &in.DeletionApproval, &out.DeletionApproval
		*out = new(DeletionApproval)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartHostSpec.
func (in *TartHostSpec) DeepCopy() *TartHostSpec {
	if in == nil {
		return nil
	}
	out := new(TartHostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartHostStatus) DeepCopyInto(out *TartHostStatus) {
	*out = *in
	if in.Inventory != nil {
		in, out := &in.Inventory, &out.Inventory
		*out = new(HostInventory)
		(*in).DeepCopyInto(*out)
	}
	if in.BootAttempts != nil {
		in, out := &in.BootAttempts, &out.BootAttempts
		*out = make([]BootAttempt, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make(v1beta2.MachineAddresses, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartHostStatus.
func (in *TartHostStatus) DeepCopy() *TartHostStatus {
	if in == nil {
		return nil
	}
	out := new(TartHostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartMachine) DeepCopyInto(out *TartMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartMachine.
func (in *TartMachine) DeepCopy() *TartMachine {
	if in == nil {
		return nil
	}
	out := new(TartMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartMachineInitializationStatus) DeepCopyInto(out *TartMachineInitializationStatus) {
	*out = *in
	if in.Provisioned != nil {
		in, out := &in.Provisioned, &out.Provisioned
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartMachineInitializationStatus.
func (in *TartMachineInitializationStatus) DeepCopy() *TartMachineInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(TartMachineInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartMachineList) DeepCopyInto(out *TartMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TartMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartMachineList.
func (in *TartMachineList) DeepCopy() *TartMachineList {
	if in == nil {
		return nil
	}
	out := new(TartMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartMachineSpec) DeepCopyInto(out *TartMachineSpec) {
	*out = *in
	if in.HostRef != nil {
		in, out := &in.HostRef, &out.HostRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.HostSelector != nil {
		in, out := &in.HostSelector, &out.HostSelector
		*out = new(HostSelector)
		(*in).DeepCopyInto(*out)
	}
	out.Image = in.Image
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartMachineSpec.
func (in *TartMachineSpec) DeepCopy() *TartMachineSpec {
	if in == nil {
		return nil
	}
	out := new(TartMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartMachineStatus) DeepCopyInto(out *TartMachineStatus) {
	*out = *in
	in.Initialization.DeepCopyInto(&out.Initialization)
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make(v1beta2.MachineAddresses, len(*in))
		copy(*out, *in)
	}
	if in.HostRef != nil {
		in, out := &in.HostRef, &out.HostRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartMachineStatus.
func (in *TartMachineStatus) DeepCopy() *TartMachineStatus {
	if in == nil {
		return nil
	}
	out := new(TartMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartMachineTemplate) DeepCopyInto(out *TartMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartMachineTemplate.
func (in *TartMachineTemplate) DeepCopy() *TartMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(TartMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartMachineTemplateList) DeepCopyInto(out *TartMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TartMachineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartMachineTemplateList.
func (in *TartMachineTemplateList) DeepCopy() *TartMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(TartMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartMachineTemplateResource) DeepCopyInto(out *TartMachineTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartMachineTemplateResource.
func (in *TartMachineTemplateResource) DeepCopy() *TartMachineTemplateResource {
	if in == nil {
		return nil
	}
	out := new(TartMachineTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartMachineTemplateResourceSpec) DeepCopyInto(out *TartMachineTemplateResourceSpec) {
	*out = *in
	if in.HostSelector != nil {
		in, out := &in.HostSelector, &out.HostSelector
		*out = new(HostSelector)
		(*in).DeepCopyInto(*out)
	}
	out.Image = in.Image
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartMachineTemplateResourceSpec.
func (in *TartMachineTemplateResourceSpec) DeepCopy() *TartMachineTemplateResourceSpec {
	if in == nil {
		return nil
	}
	out := new(TartMachineTemplateResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartMachineTemplateSpec) DeepCopyInto(out *TartMachineTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartMachineTemplateSpec.
func (in *TartMachineTemplateSpec) DeepCopy() *TartMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(TartMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartUpdatePolicy) DeepCopyInto(out *TartUpdatePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartUpdatePolicy.
func (in *TartUpdatePolicy) DeepCopy() *TartUpdatePolicy {
	if in == nil {
		return nil
	}
	out := new(TartUpdatePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WakeOnLANPowerConfig) DeepCopyInto(out *WakeOnLANPowerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WakeOnLANPowerConfig.
func (in *WakeOnLANPowerConfig) DeepCopy() *WakeOnLANPowerConfig {
	if in == nil {
		return nil
	}
	out := new(WakeOnLANPowerConfig)
	in.DeepCopyInto(out)
	return out
}
