apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../external-bootstrap

images:
- name: controller
  newName: ghcr.io/walnuts1018/cluster-api-provider-tart
  newTag: latest

patches:
- target:
    kind: Deployment
    name: controller-manager
    namespace: system
  patch: |-
    - op: add
      path: /spec/template/spec/hostNetwork
      value: true
    - op: add
      path: /spec/template/spec/dnsPolicy
      value: ClusterFirstWithHostNet
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --bootstrap-bind-address=0
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --tftp-bind-address=0
    - op: add
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent
    - op: replace
      path: /spec/template/spec/volumes/0
      value:
        name: bootloader
        emptyDir: {}
