# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default/control-plane
resources:
- ../bases/controlplane.cluster.x-k8s.io_tartcontrolplanes.yaml
- ../bases/controlplane.cluster.x-k8s.io_tartcontrolplanetemplates.yaml
# +kubebuilder:scaffold:crdkustomizeresource

labels:
- includeSelectors: true
  pairs:
    cluster.x-k8s.io/provider: control-plane-tart
