// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/walnuts1018/cluster-api-provider-tart/internal/controller"
	"github.com/walnuts1018/cluster-api-provider-tart/internal/domain/host"
	"github.com/walnuts1018/cluster-api-provider-tart/internal/domain/provisioning"
	"github.com/walnuts1018/cluster-api-provider-tart/pkg/wol"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

import (
	_ "k8s.io/client-go/plugin/pkg/client/auth"
)

// Injectors from wire.go:

func InitializeReconcilers(k8sClient client.Client, scheme2 *runtime.Scheme) (Reconcilers, error) {
	service := host.NewService(k8sClient)
	tartHostReconciler := provideTartHostReconciler(k8sClient, scheme2, service)
	wakeOnLANSender := provideWakeOnLANSender()
	provisioningService := provisioning.NewService(k8sClient, service, wakeOnLANSender)
	tartMachineReconciler := provideTartMachineReconciler(k8sClient, scheme2, service, provisioningService)
	reconcilers := provideReconcilers(tartHostReconciler, tartMachineReconciler)
	return reconcilers, nil
}

// wire.go:

type Reconcilers struct {
	TartHost    *controller.TartHostReconciler
	TartMachine *controller.TartMachineReconciler
}

func provideWakeOnLANSender() provisioning.WakeOnLANSender {
	return wol.DefaultSender()
}

func provideTartHostReconciler(k8sClient client.Client, scheme2 *runtime.Scheme, hostService host.Service) *controller.TartHostReconciler {
	return &controller.TartHostReconciler{
		Client:      k8sClient,
		Scheme:      scheme2,
		HostService: hostService,
	}
}

func provideTartMachineReconciler(
	k8sClient client.Client, scheme2 *runtime.Scheme,
	hostService host.Service,
	provisioningService provisioning.Service,
) *controller.TartMachineReconciler {
	return &controller.TartMachineReconciler{
		Client:       k8sClient,
		Scheme:       scheme2,
		HostService:  hostService,
		Provisioning: provisioningService,
	}
}

func provideReconcilers(
	tartHost *controller.TartHostReconciler,
	tartMachine *controller.TartMachineReconciler,
) Reconcilers {
	return Reconcilers{
		TartHost:    tartHost,
		TartMachine: tartMachine,
	}
}
