//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/cluster-api/api/core/v1beta2"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIEndpoint) DeepCopyInto(out *APIEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIEndpoint.
func (in *APIEndpoint) DeepCopy() *APIEndpoint {
	if in == nil {
		return nil
	}
	out := new(APIEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactPolicy) DeepCopyInto(out *ArtifactPolicy) {
	*out = *in
	if in.AllowedRegistries != nil {
		in, out := &in.AllowedRegistries, &out.AllowedRegistries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactPolicy.
func (in *ArtifactPolicy) DeepCopy() *ArtifactPolicy {
	if in == nil {
		return nil
	}
	out := new(ArtifactPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostIdentifiers) DeepCopyInto(out *HostIdentifiers) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostIdentifiers.
func (in *HostIdentifiers) DeepCopy() *HostIdentifiers {
	if in == nil {
		return nil
	}
	out := new(HostIdentifiers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostInventory) DeepCopyInto(out *HostInventory) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	out.RootDisk = in.RootDisk
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostInventory.
func (in *HostInventory) DeepCopy() *HostInventory {
	if in == nil {
		return nil
	}
	out := new(HostInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostManagement) DeepCopyInto(out *HostManagement) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostManagement.
func (in *HostManagement) DeepCopy() *HostManagement {
	if in == nil {
		return nil
	}
	out := new(HostManagement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostSelector) DeepCopyInto(out *HostSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostSelector.
func (in *HostSelector) DeepCopy() *HostSelector {
	if in == nil {
		return nil
	}
	out := new(HostSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedDisk) DeepCopyInto(out *ObservedDisk) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedDisk.
func (in *ObservedDisk) DeepCopy() *ObservedDisk {
	if in == nil {
		return nil
	}
	out := new(ObservedDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReference) DeepCopyInto(out *ResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReference.
func (in *ResourceReference) DeepCopy() *ResourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RootDeviceHints) DeepCopyInto(out *RootDeviceHints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RootDeviceHints.
func (in *RootDeviceHints) DeepCopy() *RootDeviceHints {
	if in == nil {
		return nil
	}
	out := new(RootDeviceHints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartCluster) DeepCopyInto(out *TartCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartCluster.
func (in *TartCluster) DeepCopy() *TartCluster {
	if in == nil {
		return nil
	}
	out := new(TartCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartClusterInitializationStatus) DeepCopyInto(out *TartClusterInitializationStatus) {
	*out = *in
	if in.Provisioned != nil {
		in, out := &in.Provisioned, &out.Provisioned
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartClusterInitializationStatus.
func (in *TartClusterInitializationStatus) DeepCopy() *TartClusterInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(TartClusterInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartClusterList) DeepCopyInto(out *TartClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TartCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartClusterList.
func (in *TartClusterList) DeepCopy() *TartClusterList {
	if in == nil {
		return nil
	}
	out := new(TartClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartClusterSpec) DeepCopyInto(out *TartClusterSpec) {
	*out = *in
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	in.ArtifactPolicy.DeepCopyInto(&out.ArtifactPolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartClusterSpec.
func (in *TartClusterSpec) DeepCopy() *TartClusterSpec {
	if in == nil {
		return nil
	}
	out := new(TartClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartClusterStatus) DeepCopyInto(out *TartClusterStatus) {
	*out = *in
	in.Initialization.DeepCopyInto(&out.Initialization)
	if in.FailureDomains != nil {
		in, out := &in.FailureDomains, &out.FailureDomains
		*out = make([]v1beta2.FailureDomain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartClusterStatus.
func (in *TartClusterStatus) DeepCopy() *TartClusterStatus {
	if in == nil {
		return nil
	}
	out := new(TartClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartClusterTemplate) DeepCopyInto(out *TartClusterTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartClusterTemplate.
func (in *TartClusterTemplate) DeepCopy() *TartClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(TartClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartClusterTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartClusterTemplateList) DeepCopyInto(out *TartClusterTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TartClusterTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartClusterTemplateList.
func (in *TartClusterTemplateList) DeepCopy() *TartClusterTemplateList {
	if in == nil {
		return nil
	}
	out := new(TartClusterTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartClusterTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartClusterTemplateResource) DeepCopyInto(out *TartClusterTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartClusterTemplateResource.
func (in *TartClusterTemplateResource) DeepCopy() *TartClusterTemplateResource {
	if in == nil {
		return nil
	}
	out := new(TartClusterTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartClusterTemplateSpec) DeepCopyInto(out *TartClusterTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartClusterTemplateSpec.
func (in *TartClusterTemplateSpec) DeepCopy() *TartClusterTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(TartClusterTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartHost) DeepCopyInto(out *TartHost) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartHost.
func (in *TartHost) DeepCopy() *TartHost {
	if in == nil {
		return nil
	}
	out := new(TartHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartHost) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartHostList) DeepCopyInto(out *TartHostList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TartHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartHostList.
func (in *TartHostList) DeepCopy() *TartHostList {
	if in == nil {
		return nil
	}
	out := new(TartHostList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartHostList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartHostOperation) DeepCopyInto(out *TartHostOperation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartHostOperation.
func (in *TartHostOperation) DeepCopy() *TartHostOperation {
	if in == nil {
		return nil
	}
	out := new(TartHostOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartHostOperation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartHostOperationList) DeepCopyInto(out *TartHostOperationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TartHostOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartHostOperationList.
func (in *TartHostOperationList) DeepCopy() *TartHostOperationList {
	if in == nil {
		return nil
	}
	out := new(TartHostOperationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartHostOperationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartHostOperationSpec) DeepCopyInto(out *TartHostOperationSpec) {
	*out = *in
	out.HostRef = in.HostRef
	if in.MachineRef != nil {
		in, out := &in.MachineRef, &out.MachineRef
		*out = new(ResourceReference)
		**out = **in
	}
	if in.TargetArtifactGeneration != nil {
		in, out := &in.TargetArtifactGeneration, &out.TargetArtifactGeneration
		*out = new(int64)
		**out = **in
	}
	in.Deadline.DeepCopyInto(&out.Deadline)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartHostOperationSpec.
func (in *TartHostOperationSpec) DeepCopy() *TartHostOperationSpec {
	if in == nil {
		return nil
	}
	out := new(TartHostOperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartHostOperationStatus) DeepCopyInto(out *TartHostOperationStatus) {
	*out = *in
	if in.SnapshotRef != nil {
		in, out := &in.SnapshotRef, &out.SnapshotRef
		*out = new(ResourceReference)
		**out = **in
	}
	if in.CompletedSteps != nil {
		in, out := &in.CompletedSteps, &out.CompletedSteps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SessionTokenExpiresAt != nil {
		in, out := &in.SessionTokenExpiresAt, &out.SessionTokenExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartHostOperationStatus.
func (in *TartHostOperationStatus) DeepCopy() *TartHostOperationStatus {
	if in == nil {
		return nil
	}
	out := new(TartHostOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartHostSpec) DeepCopyInto(out *TartHostSpec) {
	*out = *in
	out.Identifiers = in.Identifiers
	out.RootDeviceHints = in.RootDeviceHints
	in.Management.DeepCopyInto(&out.Management)
	if in.ConsumerRef != nil {
		in, out := &in.ConsumerRef, &out.ConsumerRef
		*out = new(ResourceReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartHostSpec.
func (in *TartHostSpec) DeepCopy() *TartHostSpec {
	if in == nil {
		return nil
	}
	out := new(TartHostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartHostStatus) DeepCopyInto(out *TartHostStatus) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]Capability, len(*in))
		copy(*out, *in)
	}
	in.Inventory.DeepCopyInto(&out.Inventory)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartHostStatus.
func (in *TartHostStatus) DeepCopy() *TartHostStatus {
	if in == nil {
		return nil
	}
	out := new(TartHostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartMachine) DeepCopyInto(out *TartMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartMachine.
func (in *TartMachine) DeepCopy() *TartMachine {
	if in == nil {
		return nil
	}
	out := new(TartMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartMachineInitializationStatus) DeepCopyInto(out *TartMachineInitializationStatus) {
	*out = *in
	if in.Provisioned != nil {
		in, out := &in.Provisioned, &out.Provisioned
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartMachineInitializationStatus.
func (in *TartMachineInitializationStatus) DeepCopy() *TartMachineInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(TartMachineInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartMachineList) DeepCopyInto(out *TartMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TartMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartMachineList.
func (in *TartMachineList) DeepCopy() *TartMachineList {
	if in == nil {
		return nil
	}
	out := new(TartMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartMachineSpec) DeepCopyInto(out *TartMachineSpec) {
	*out = *in
	out.Image = in.Image
	in.HostSelector.DeepCopyInto(&out.HostSelector)
	out.UpdatePolicy = in.UpdatePolicy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartMachineSpec.
func (in *TartMachineSpec) DeepCopy() *TartMachineSpec {
	if in == nil {
		return nil
	}
	out := new(TartMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartMachineStatus) DeepCopyInto(out *TartMachineStatus) {
	*out = *in
	in.Initialization.DeepCopyInto(&out.Initialization)
	if in.HostRef != nil {
		in, out := &in.HostRef, &out.HostRef
		*out = new(ResourceReference)
		**out = **in
	}
	if in.OperationRef != nil {
		in, out := &in.OperationRef, &out.OperationRef
		*out = new(ResourceReference)
		**out = **in
	}
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make(v1beta2.MachineAddresses, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartMachineStatus.
func (in *TartMachineStatus) DeepCopy() *TartMachineStatus {
	if in == nil {
		return nil
	}
	out := new(TartMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartMachineTemplate) DeepCopyInto(out *TartMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartMachineTemplate.
func (in *TartMachineTemplate) DeepCopy() *TartMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(TartMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartMachineTemplateList) DeepCopyInto(out *TartMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TartMachineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartMachineTemplateList.
func (in *TartMachineTemplateList) DeepCopy() *TartMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(TartMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartMachineTemplateResource) DeepCopyInto(out *TartMachineTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartMachineTemplateResource.
func (in *TartMachineTemplateResource) DeepCopy() *TartMachineTemplateResource {
	if in == nil {
		return nil
	}
	out := new(TartMachineTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartMachineTemplateResourceSpec) DeepCopyInto(out *TartMachineTemplateResourceSpec) {
	*out = *in
	out.Image = in.Image
	in.HostSelector.DeepCopyInto(&out.HostSelector)
	out.UpdatePolicy = in.UpdatePolicy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartMachineTemplateResourceSpec.
func (in *TartMachineTemplateResourceSpec) DeepCopy() *TartMachineTemplateResourceSpec {
	if in == nil {
		return nil
	}
	out := new(TartMachineTemplateResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartMachineTemplateSpec) DeepCopyInto(out *TartMachineTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartMachineTemplateSpec.
func (in *TartMachineTemplateSpec) DeepCopy() *TartMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(TartMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdatePolicy) DeepCopyInto(out *UpdatePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdatePolicy.
func (in *UpdatePolicy) DeepCopy() *UpdatePolicy {
	if in == nil {
		return nil
	}
	out := new(UpdatePolicy)
	in.DeepCopyInto(out)
	return out
}
