//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineDeletionSpec) DeepCopyInto(out *MachineDeletionSpec) {
	*out = *in
	if in.NodeDrainTimeoutSeconds != nil {
		in, out := &in.NodeDrainTimeoutSeconds, &out.NodeDrainTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.NodeVolumeDetachTimeoutSeconds != nil {
		in, out := &in.NodeVolumeDetachTimeoutSeconds, &out.NodeVolumeDetachTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.NodeDeletionTimeoutSeconds != nil {
		in, out := &in.NodeDeletionTimeoutSeconds, &out.NodeDeletionTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineDeletionSpec.
func (in *MachineDeletionSpec) DeepCopy() *MachineDeletionSpec {
	if in == nil {
		return nil
	}
	out := new(MachineDeletionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineTemplateSpec) DeepCopyInto(out *MachineTemplateSpec) {
	*out = *in
	out.InfrastructureRef = in.InfrastructureRef
	in.Deletion.DeepCopyInto(&out.Deletion)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineTemplateSpec.
func (in *MachineTemplateSpec) DeepCopy() *MachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(MachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartControlPlane) DeepCopyInto(out *TartControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartControlPlane.
func (in *TartControlPlane) DeepCopy() *TartControlPlane {
	if in == nil {
		return nil
	}
	out := new(TartControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartControlPlaneInitializationStatus) DeepCopyInto(out *TartControlPlaneInitializationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartControlPlaneInitializationStatus.
func (in *TartControlPlaneInitializationStatus) DeepCopy() *TartControlPlaneInitializationStatus {
	if in == nil {
		return nil
	}
	out := new(TartControlPlaneInitializationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartControlPlaneKubernetesVersion) DeepCopyInto(out *TartControlPlaneKubernetesVersion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartControlPlaneKubernetesVersion.
func (in *TartControlPlaneKubernetesVersion) DeepCopy() *TartControlPlaneKubernetesVersion {
	if in == nil {
		return nil
	}
	out := new(TartControlPlaneKubernetesVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartControlPlaneList) DeepCopyInto(out *TartControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TartControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartControlPlaneList.
func (in *TartControlPlaneList) DeepCopy() *TartControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(TartControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartControlPlaneSpec) DeepCopyInto(out *TartControlPlaneSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.MachineTemplate.DeepCopyInto(&out.MachineTemplate)
	out.BootstrapConfigTemplate = in.BootstrapConfigTemplate
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartControlPlaneSpec.
func (in *TartControlPlaneSpec) DeepCopy() *TartControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(TartControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartControlPlaneStatus) DeepCopyInto(out *TartControlPlaneStatus) {
	*out = *in
	out.Initialization = in.Initialization
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]TartControlPlaneKubernetesVersion, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartControlPlaneStatus.
func (in *TartControlPlaneStatus) DeepCopy() *TartControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(TartControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartControlPlaneTemplate) DeepCopyInto(out *TartControlPlaneTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartControlPlaneTemplate.
func (in *TartControlPlaneTemplate) DeepCopy() *TartControlPlaneTemplate {
	if in == nil {
		return nil
	}
	out := new(TartControlPlaneTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartControlPlaneTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartControlPlaneTemplateList) DeepCopyInto(out *TartControlPlaneTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TartControlPlaneTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartControlPlaneTemplateList.
func (in *TartControlPlaneTemplateList) DeepCopy() *TartControlPlaneTemplateList {
	if in == nil {
		return nil
	}
	out := new(TartControlPlaneTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TartControlPlaneTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartControlPlaneTemplateResource) DeepCopyInto(out *TartControlPlaneTemplateResource) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartControlPlaneTemplateResource.
func (in *TartControlPlaneTemplateResource) DeepCopy() *TartControlPlaneTemplateResource {
	if in == nil {
		return nil
	}
	out := new(TartControlPlaneTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TartControlPlaneTemplateSpec) DeepCopyInto(out *TartControlPlaneTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TartControlPlaneTemplateSpec.
func (in *TartControlPlaneTemplateSpec) DeepCopy() *TartControlPlaneTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(TartControlPlaneTemplateSpec)
	in.DeepCopyInto(out)
	return out
}
