# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/infrastructure.cluster.x-k8s.io_tartclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_tartclustertemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_tarthosts.yaml
- bases/infrastructure.cluster.x-k8s.io_tartmachines.yaml
- bases/infrastructure.cluster.x-k8s.io_tartmachinetemplates.yaml

# +kubebuilder:scaffold:crdkustomizeresource

patches:
- patch: |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: tartclusters.infrastructure.cluster.x-k8s.io
      labels:
        cluster.x-k8s.io/v1beta2: v1alpha1
  target:
    kind: CustomResourceDefinition
    name: tartclusters.infrastructure.cluster.x-k8s.io
- patch: |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: tartclustertemplates.infrastructure.cluster.x-k8s.io
      labels:
        cluster.x-k8s.io/v1beta2: v1alpha1
  target:
    kind: CustomResourceDefinition
    name: tartclustertemplates.infrastructure.cluster.x-k8s.io
- patch: |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: tartmachines.infrastructure.cluster.x-k8s.io
      labels:
        cluster.x-k8s.io/v1beta2: v1alpha1
  target:
    kind: CustomResourceDefinition
    name: tartmachines.infrastructure.cluster.x-k8s.io
- patch: |-
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: tartmachinetemplates.infrastructure.cluster.x-k8s.io
      labels:
        cluster.x-k8s.io/v1beta2: v1alpha1
  target:
    kind: CustomResourceDefinition
    name: tartmachinetemplates.infrastructure.cluster.x-k8s.io
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml

labels:
- includeSelectors: true
  pairs:
    cluster.x-k8s.io/provider: infrastructure-tart
