package network

import (
	"encoding/json"
	"errors"
	"fmt"
	"net"
)

var ErrInvalidMACAddress = errors.New("invalid MAC address")

// MACAddressは正規化済みのEUI-48を表す値オブジェクトである。ゼロ値は未設定を表す。
// MarshalJSON/UnmarshalJSONで文字列表現へ変換するため、CRD schema上もtype: stringとして
// 扱う必要がある(型定義自体へmarkerを付与することで、フィールド側の個別markerとの
// allOf衝突(struct構造由来のtype:objectとの'conflicting types'エラー)を避ける)。
// +kubebuilder:validation:Type=string
// +kubebuilder:validation:Pattern="^([0-9a-fA-F]{2}[:-]){5}([0-9a-fA-F]{2})$"
type MACAddress struct {
	// json tagはcontroller-genのJSON tag未設定警告を避けるためのものであり、実際のシリアライズは
	// MarshalJSON/UnmarshalJSON(下記)が担う(encoding/jsonは非exportedフィールドを常に無視する)。
	value [6]byte `json:"-"`
	set   bool    `json:"-"`
}

// ParseMACAddressは一般的なMACアドレス表記を受け付け、EUI-48として正規化する。
func ParseMACAddress(value string) (MACAddress, error) {
	parsed, err := net.ParseMAC(value)
	if err != nil || len(parsed) != len(MACAddress{}.value) {
		return MACAddress{}, fmt.Errorf("%w: %q", ErrInvalidMACAddress, value)
	}

	var address MACAddress
	copy(address.value[:], parsed)
	address.set = true

	return address, nil
}

// IsZeroはMACアドレスが未設定かを返す。
func (address MACAddress) IsZero() bool {
	return !address.set
}

// Stringは小文字コロン区切り形式を返す。未設定の場合は空文字列を返す。
func (address MACAddress) String() string {
	if address.IsZero() {
		return ""
	}

	return net.HardwareAddr(address.value[:]).String()
}

// BytesはMACアドレスのコピーを返す。未設定の場合はnilを返す。
func (address MACAddress) Bytes() []byte {
	if address.IsZero() {
		return nil
	}

	value := make([]byte, len(address.value))
	copy(value, address.value[:])
	return value
}

// Arrayは固定長配列と設定有無を返す。EUI-48としての長さを呼び出し側で意識する必要がない。
func (address MACAddress) Array() ([6]byte, bool) {
	return address.value, address.set
}

// DeepCopyIntoはautogenerated deepcopyを満たすためのshallow copyである。
func (in *MACAddress) DeepCopyInto(out *MACAddress) {
	*out = *in
}

// DeepCopyはMACAddressのdeep copyを返す。
func (in *MACAddress) DeepCopy() *MACAddress {
	if in == nil {
		return nil
	}
	out := new(MACAddress)
	in.DeepCopyInto(out)
	return out
}

func (address MACAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(address.String())
}

func (address *MACAddress) UnmarshalJSON(value []byte) error {
	var text *string
	if err := json.Unmarshal(value, &text); err != nil {
		return fmt.Errorf("%w: %v", ErrInvalidMACAddress, err)
	}

	if text == nil {
		*address = MACAddress{}
		return nil
	}

	return address.UnmarshalText([]byte(*text))
}

func (address MACAddress) MarshalText() ([]byte, error) {
	return []byte(address.String()), nil
}

func (address *MACAddress) UnmarshalText(value []byte) error {
	if len(value) == 0 {
		*address = MACAddress{}
		return nil
	}

	parsed, err := ParseMACAddress(string(value))
	if err != nil {
		return err
	}

	*address = parsed
	return nil
}
