[Match]
Distribution=debian

[Distribution]
Repositories=

[Content]
Packages=
          linux-image-amd64
          initramfs-tools
          cryptsetup-initramfs
          systemd-boot
          cloud-init
          containerd
          conntrack
          curl
          ebtables
          ethtool
          socat
          kubeadm=1.36.2-2.1
          kubectl=1.36.2-2.1
          kubelet=1.36.2-2.1
          kubernetes-cni=1.9.1-1.1
          cri-tools=1.36.0-1.1
