apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: cluster-api-provider-tart
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: cluster-api-provider-tart
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: cluster-api-provider-tart
    spec:
      hostNetwork: true
      dnsPolicy: Default
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ .Values.serviceAccount.name | default "controller-manager" }}
      terminationGracePeriodSeconds: 10
      containers:
      - name: manager
        command:
        - /manager
        args:
        - --leader-elect
        - --health-probe-bind-address=:8081
        - --bootstrap-advertise-address=$(POD_IP)
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 67
          name: bootp
          protocol: UDP
        - containerPort: 69
          name: tftp
          protocol: UDP
        - containerPort: 8082
          name: ipxe
          protocol: TCP
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        volumeMounts:
        - name: bootloader
          mountPath: /var/lib/tftpboot
          readOnly: true
      volumes:
      - name: bootloader
        image:
          reference: "{{ .Values.ipxe.image.repository }}:{{ .Values.ipxe.image.tag }}"
          pullPolicy: {{ .Values.ipxe.image.pullPolicy }}
