apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster-api-provider-tart.fullname" . }}-controller-manager-ipxe
  labels:
    cluster.x-k8s.io/provider: infrastructure-tart
  {{- include "cluster-api-provider-tart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ipxe.type }}
  selector:
    app.kubernetes.io/name: cluster-api-provider-tart
    cluster.x-k8s.io/provider: infrastructure-tart
    control-plane: controller-manager
    {{- include "cluster-api-provider-tart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.ipxe.ports | toYaml | nindent 2 }}
