apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: cluster-api-provider-tart
    app.kubernetes.io/managed-by: {{ .Release.Service }}
