// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/walnuts1018/cluster-api-provider-tart/internal/adapter/driver/redfish"
	"github.com/walnuts1018/cluster-api-provider-tart/internal/adapter/driver/wol"
	"github.com/walnuts1018/cluster-api-provider-tart/internal/adapter/k8s/allocation"
	"github.com/walnuts1018/cluster-api-provider-tart/internal/adapter/k8s/bootstraptoken"
	"github.com/walnuts1018/cluster-api-provider-tart/internal/adapter/k8s/drivercapability"
	"github.com/walnuts1018/cluster-api-provider-tart/internal/adapter/k8s/drivertarget"
	"github.com/walnuts1018/cluster-api-provider-tart/internal/adapter/k8s/host"
	"github.com/walnuts1018/cluster-api-provider-tart/internal/adapter/k8s/machinehealth"
	"github.com/walnuts1018/cluster-api-provider-tart/internal/adapter/k8s/operation"
	"github.com/walnuts1018/cluster-api-provider-tart/internal/adapter/k8s/v1beta1host"
	bootstraptoken2 "github.com/walnuts1018/cluster-api-provider-tart/internal/application/bootstraptoken"
	"github.com/walnuts1018/cluster-api-provider-tart/internal/application/driver"
	host2 "github.com/walnuts1018/cluster-api-provider-tart/internal/application/host"
	"github.com/walnuts1018/cluster-api-provider-tart/internal/application/initialprovisioning"
	"github.com/walnuts1018/cluster-api-provider-tart/internal/application/provisioning"
	"github.com/walnuts1018/cluster-api-provider-tart/internal/controller"
	driver2 "github.com/walnuts1018/cluster-api-provider-tart/internal/domain/driver"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// Injectors from wire.go:

func InitializeReconcilers(k8sClient client.Client, scheme *runtime.Scheme) (Reconcilers, error) {
	service := host.NewService(k8sClient)
	tartHostReconciler := provideTartHostReconciler(k8sClient, scheme, service)
	bootstraptokenService := bootstraptoken.NewService(k8sClient)
	adapter := wol.Default()
	redfishAdapter := redfish.New()
	registry, err := provideDriverRegistry(adapter, redfishAdapter)
	if err != nil {
		return Reconcilers{}, err
	}
	driverService, err := driver.NewService(registry)
	if err != nil {
		return Reconcilers{}, err
	}
	provisioningService := provisioning.NewService(service, service, driverService)
	tartMachineReconciler := provideTartMachineReconciler(k8sClient, scheme, service, bootstraptokenService, provisioningService)
	tartClusterReconciler := provideTartClusterReconciler(k8sClient, scheme)
	tartMachineTemplateReconciler := provideTartMachineTemplateReconciler(k8sClient, scheme)
	allocationService := allocation.NewService(k8sClient)
	observer := machinehealth.NewObserver(k8sClient)
	v1beta1hostService := v1beta1host.NewService(k8sClient)
	operationService := operation.NewService(k8sClient)
	orchestrator := initialprovisioning.NewOrchestrator(allocationService, v1beta1hostService, operationService)
	tartMachineV1Beta1Reconciler := provideTartMachineV1Beta1Reconciler(k8sClient, allocationService, observer, orchestrator)
	drivertargetService := drivertarget.NewService(k8sClient)
	drivercapabilityService := drivercapability.NewService(driverService, v1beta1hostService)
	tartHostOperationReconciler := provideTartHostOperationReconciler(k8sClient, scheme, driverService, driverService, v1beta1hostService, drivertargetService, drivercapabilityService)
	reconcilers := provideReconcilers(tartHostReconciler, tartMachineReconciler, tartClusterReconciler, tartMachineTemplateReconciler, tartMachineV1Beta1Reconciler, tartHostOperationReconciler)
	return reconcilers, nil
}

// wire.go:

type Reconcilers struct {
	TartHost            *controller.TartHostReconciler
	TartMachine         *controller.TartMachineReconciler
	TartCluster         *controller.TartClusterReconciler
	TartMachineTemplate *controller.TartMachineTemplateReconciler
	TartMachineV1Beta1  *controller.TartMachineV1Beta1Reconciler
	TartHostOperation   *controller.TartHostOperationReconciler
}

func provideDriverRegistry(
	wolDriver *wol.Adapter,
	redfishDriver *redfish.Adapter,
) (*driver.Registry, error) {
	registry := driver.NewRegistry()
	if err := registry.RegisterPowerOn(driver2.WoL, wolDriver); err != nil {
		return nil, err
	}
	if err := registry.RegisterPowerOn(driver2.Redfish, redfishDriver); err != nil {
		return nil, err
	}
	if err := registry.RegisterPowerOff(driver2.Redfish, redfishDriver); err != nil {
		return nil, err
	}
	if err := registry.RegisterPowerStateObserver(driver2.Redfish, redfishDriver); err != nil {
		return nil, err
	}
	if err := registry.RegisterBootOverride(driver2.Redfish, redfishDriver); err != nil {
		return nil, err
	}
	if err := registry.RegisterVirtualMedia(driver2.Redfish, redfishDriver); err != nil {
		return nil, err
	}
	if err := registry.RegisterCapabilityDiscoverer(driver2.Redfish, redfishDriver); err != nil {
		return nil, err
	}
	return registry, nil
}

func provideTartHostReconciler(k8sClient client.Client, scheme *runtime.Scheme, hostService host2.Service) *controller.TartHostReconciler {
	return &controller.TartHostReconciler{
		Client:      k8sClient,
		Scheme:      scheme,
		HostService: hostService,
	}
}

func provideTartMachineReconciler(
	k8sClient client.Client,
	scheme *runtime.Scheme,
	hostService host2.Service,
	tokenService bootstraptoken2.Service,
	provisioningService provisioning.Service,
) *controller.TartMachineReconciler {
	return &controller.TartMachineReconciler{
		Client:       k8sClient,
		Scheme:       scheme,
		HostService:  hostService,
		TokenService: tokenService,
		Provisioning: provisioningService,
	}
}

func provideTartClusterReconciler(k8sClient client.Client, scheme *runtime.Scheme) *controller.TartClusterReconciler {
	return &controller.TartClusterReconciler{
		Client: k8sClient,
		Scheme: scheme,
	}
}

func provideTartMachineTemplateReconciler(k8sClient client.Client, scheme *runtime.Scheme) *controller.TartMachineTemplateReconciler {
	return &controller.TartMachineTemplateReconciler{
		Client: k8sClient,
		Scheme: scheme,
	}
}

func provideTartMachineV1Beta1Reconciler(
	k8sClient client.Client,
	hostReferences controller.HostReferenceService,
	nodeHealth controller.NodeHealthObserver,
	provisioner controller.ProvisionOrchestrator,
) *controller.TartMachineV1Beta1Reconciler {
	return &controller.TartMachineV1Beta1Reconciler{
		Client:         k8sClient,
		HostReferences: hostReferences,
		NodeHealth:     nodeHealth,
		Provisioner:    provisioner,
	}
}

func provideTartHostOperationReconciler(
	k8sClient client.Client,
	scheme *runtime.Scheme,
	powerOn controller.OperationPowerOnService,
	prepareBoot controller.OperationBootPreparationService,
	hostPhase controller.OperationHostPhaseService,
	targets controller.OperationDriverTargetBuilder,
	driverCapabilities controller.OperationDriverCapabilityObserver,
) *controller.TartHostOperationReconciler {
	return &controller.TartHostOperationReconciler{
		Client:             k8sClient,
		Scheme:             scheme,
		PowerOn:            powerOn,
		PrepareBoot:        prepareBoot,
		HostPhase:          hostPhase,
		Targets:            targets,
		DriverCapabilities: driverCapabilities,
	}
}

func provideReconcilers(
	tartHost *controller.TartHostReconciler,
	tartMachine *controller.TartMachineReconciler,
	tartCluster *controller.TartClusterReconciler,
	tartMachineTemplate *controller.TartMachineTemplateReconciler,
	tartMachineV1Beta1 *controller.TartMachineV1Beta1Reconciler,
	tartHostOperation *controller.TartHostOperationReconciler,
) Reconcilers {
	return Reconcilers{
		TartHost:            tartHost,
		TartMachine:         tartMachine,
		TartCluster:         tartCluster,
		TartMachineTemplate: tartMachineTemplate,
		TartMachineV1Beta1:  tartMachineV1Beta1,
		TartHostOperation:   tartHostOperation,
	}
}
